pgns:
  vessel_heading:
    pgn: 127250
    description: "Vessel Heading"
    parameters:
      heading:
        description: "Heading"
        unit: "°"
        min: 0
        max: 359
        step: 1

  speed:
    pgn: 128259
    description: "Speed"
    parameters:
      speed:
        description: "Speed"
        unit: "kts"
        min: 0
        max: 50
        step: 0.1

  engine_parameters:
    pgn: 127488
    description: "Engine Parameters, Rapid Update"
    parameters:
      engine_instance:
        description: "Engine Instance"
        unit: ""
        min: 0
        max: 3
        step: 1
      rpm:
        description: "Engine Speed"
        unit: "rpm"
        min: 0
        max: 10000
        step: 50
      boost_pressure:
        description: "Boost Pressure"
        unit: "PSI"
        min: 0
        max: 400
        step: 1
      tilt_trim:
        description: "Tilt/Trim Position"
        unit: "%"
        min: -100
        max: 100
        step: 1

  battery_status:
    pgn: 127508
    description: "Battery Status"
    parameters:
      voltage:
        description: "Voltage"
        unit: "V"
        min: 0
        max: 16
        step: 0.1 