
default_pgns:
  - pgnId: 127488
    fields:
      - name: Speed
        defaultValue: 500
      - name: Tilt/Trim
        defaultValue: 15
      - name: Boost Pressure
        defaultValue: 25
      - name: Instance 
        defaultValue: 1

  - pgnId: 127508
    fields:
      - name: Instance
        defaultValue: 1
      - name: Voltage 
        defaultValue: 48
      - name: Current
        defaultValue: 10
      - name: Temperature
        defaultValue: 293.15

  - pgnId: 128259
    fields:
      - name: Speed Water Referenced
        defaultValue: 13
      - name: Speed Water Referenced Type
        defaultValue: 1
      - name: Speed Ground Referenced
        defaultValue: 19
      - name: Speed Direction
        defaultValue: 3.0