pgns:
  vessel_heading:
    pgn: 127250
    description: "Vessel Heading"
    system: navigation
    parameters:
      heading:
        description: "Heading"
        unit: "°"
        min: 0
        max: 359
        step: 1

  speed:
    pgn: 128259
    description: "Speed"
    system: navigation
    parameters:
      speed:
        description: "Speed"
        unit: "kts"
        min: 0
        max: 50
        step: 0.1

  engine_parameters:
    pgn: 127488
    description: "Engine Parameters"
    system: engine
    parameters:
      rpm:
        description: "RPM"
        unit: "rpm"
        min: 0
        max: 4000
        step: 50
      oil_pressure:
        description: "Oil Pressure"
        unit: "PSI"
        min: 0
        max: 100
        step: 1
      coolant_temp:
        description: "Coolant Temperature"
        unit: "°C"
        min: 0
        max: 120
        step: 1

  battery_status:
    pgn: 127508
    description: "Battery Status"
    system: electrical
    parameters:
      voltage:
        description: "Voltage"
        unit: "V"
        min: 0
        max: 16
        step: 0.1 